import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { Navbar } from './navbar'
import { Foot } from './foot'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hidrantes Fácil Canoas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
      <Navbar></Navbar>
        <section className='h-[550px]'>
          <Providers>
            {children}
          </Providers>
        </section>
      </body>
    </html>
  )
}