import Link from 'next/link'
import Image from 'next/image'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="container">
          <header>
            <div className="titulo">
              <Image
                src="/brasao-bombeiros.png"
                alt="Brasão Corpo de Bombeiros"
                width={165}
                height={160}
              />
              <div className="escrita">
                <h1>LOCALIZA FÁCIL - HIDRANTES PÚBLICOS</h1>
                <h2>CORPO DE BOMBEIROS MILITAR DE CANOAS/RS</h2>
              </div>
            </div>
            <ul className="topnav">
              <li className="left">
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/contatos">Hidrantes</Link>
              </li>
              <li className='right'>
                <Link href="/sobre">?</Link>
              </li>
            </ul>
          </header>
          <main>
            <section>
              {children}

            </section>
          </main>
          <footer><h2>Copyright © 2023 - CBMRS - Canoas/RS</h2></footer>
        </div>
      </body>
    </html>
  )
}